spring:
  application:
    name: exception

messages:
  basename: messages, errors


server:
  error:
    whitelabel:
      enabled: false
    include-exception: false
    include-message: always
    include-stacktrace: never
    include-binding-errors: never