spring:
  application:
    name: exception


server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    path: /error
#    include-message: always
#    include-stacktrace: always
#    include-binding-errors: always