spring:
  application:
    name: exception


server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: never
    include-stacktrace: never
    include-binding-errors: never